DROP DATABASE IF EXISTS teste;

DROP ROLE IF EXISTS usuario;

CREATE ROLE usuario LOGIN
  UNENCRYPTED PASSWORD 'senha'
  SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;

CREATE DATABASE teste
  WITH OWNER = usuario
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'pt_BR.UTF-8'
       LC_CTYPE = 'pt_BR.UTF-8'
       CONNECTION LIMIT = -1;
